options:
  snap-mode:
    type: string
    default: "agent"
    description: >-
      'Configure the license-manager snap to run in server or agent mode.
       Default: agent'
  slurmctld_prolog_path:
    type: string
    default: /snap/slurm-license/current/bin/slurmctldprolog
    description: >-
      'SlurmctldProlog path.'
  slurmctld_epilog_path:
    type: string
    default: /snap/slurm-license/current/bin/slurmctldepilog
    description: >-
      'SlurmctldEpilog path.'
  sentry_dsn:
    type: string
    default: ""
    description: >-
      'Setting this to a valid sentry dsn will enable sentry traceback reporting.'
