name: Release

on:
  push:
    branches:
      - main

jobs:
  build-charm:
    name: "Build the charms"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: "Install charmcraft and build charms"
        run: |
          pip install charmcraft
          charmcraft build
      - name: Cache built charms
        if: ${{ success() }}
        id: license-manager-charm
        uses: actions/cache@v2
        with:
          path: ${{ steps.vars.outputs.charm_file }}
          key: license-manager-charm-${{ hashFiles('*.charm') }}

    outputs:
      charm_file: ${{ steps.vars.outputs.charm_file }}
      charm_hash: ${{ steps.vars.outputs.charm_hash }}

  release-jobbergate-charm-to-edge:
    name: "Push slurm charms to s3"
    runs-on: "ubuntu-latest"
    needs: [build-charm]
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: "Restore built charms"
        uses: actions/cache@v2
        with:
          path: ${{ needs.build-charm.outputs.charm_file}}
          key: license-manager-charm-${{ needs.build-charm.outputs.charm_hash }}

      - name: "Push charms to s3"
        shell: bash
        run: |
          aws s3 cp license-manager.charm s3://omnivector-public-assets/charms/charm-license-manager/edge/
